language: android
jdk: oraclejdk8
dist: trusty

env:
  global:
  
android:
  components:
    - tools
    - build-tools-29.0.3
    - android-29
    # additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
    
    
  licenses:
      - 'android-sdk-preview-license-52d11cd2'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
  - chmod +x TreatYourShelf/gradlew
  - yes | sdkmanager "platforms;android-30"

before_script:
  - chmod +x TreatYourShelf/gradlew
  - cd TreatYourShelf

script:
  - ./gradlew clean build
  - ./gradlew test
